on:
  push:
    branches:
      - main
name: 🚀 Deploy praidev on push
jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    - name: 🗄 list all files
      run: ls -lha
    - name: 📡 SSH conect and sync files
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          [ -d apps/triplice_3d/ ] && cd apps/triplice_3d/ || { mkdir -p apps/ && cd apps/; }
          [ -d ".git" ] && git pull || { git clone git@github.com:nilson-santos/triplice_3d.git && cd triplice_3d/; }
          [ -e ".env" ] && docker compose up -d --build && docker image prune -af || echo "NOT FOUND .env FILE"